language: python
python: 
  - "3.6"
services: 
  - mysql
env: 
  -DJANGO=2.1 DB=mysql
install: 
  - pip install -r requirements.txt
  - pip install coverage 
  - pip install codecov
before_script: 
  - mysql -e 'create database test;' -u root
script: 
  - coverage run --source='.' --omit='manage.py' manage.py test
after_success:
  - codecov