language: python
python: 
  - "3.6"
services: 
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
env: 
  -DJANGO=2.1 
install: 
  - pip install -r requirements.txt
  - pip install coverage 
  - pip install codecov
before_script: 
  - psql -c "CREATE DATABASE test;" -U postgres
script: 
  - coverage run --source='.' --omit='manage.py' manage.py test
after_success:
  - codecov